permalink: pretty

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename/
  - scope:
      path: "index"
    values:
      permalink: /

include:
  - "index"
  - "mixing"
  - "mastering"
  - "production"
  - "livesound"
  - "privacypolicy"

exclude:
  - ".DS_Store"
